import * as fs from 'fs';
import * as path from 'path';
import { BundleAnalysis } from '../types';
import { formatBytes } from './fileHelper';

export class ReportGenerator {
  /**
   * Generate an HTML report
   */
  static generateHtmlReport(analysis: BundleAnalysis, outputPath: string): void {
    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Bundle Analysis Report</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      max-width: 1200px;
      margin: 0 auto;
      padding: 20px;
      background: #f5f5f5;
    }
    h1 { color: #333; }
    .summary {
      background: white;
      padding: 20px;
      border-radius: 8px;
      margin: 20px 0;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    table {
      width: 100%;
      border-collapse: collapse;
      background: white;
      margin: 20px 0;
      border-radius: 8px;
      overflow: hidden;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    th, td {
      padding: 12px;
      text-align: left;
      border-bottom: 1px solid #eee;
    }
    th {
      background: #667eea;
      color: white;
      font-weight: 600;
    }
    .optimization {
      background: white;
      padding: 15px;
      margin: 10px 0;
      border-left: 4px solid;
      border-radius: 4px;
    }
    .optimization.high { border-color: #ef4444; }
    .optimization.medium { border-color: #f59e0b; }
    .optimization.low { border-color: #10b981; }
  </style>
</head>
<body>
  <h1>📦 React Native Bundle Analysis Report</h1>

  <div class="summary">
    <h2>Summary</h2>
    <p><strong>Total Bundle Size:</strong> ${formatBytes(analysis.totalSize)}</p>
    <p><strong>Your Code:</strong> ${formatBytes(analysis.yourCodeSize)} (${((analysis.yourCodeSize / analysis.totalSize) * 100).toFixed(2)}%)</p>
    <p><strong>node_modules:</strong> ${formatBytes(analysis.nodeModulesSize)} (${((analysis.nodeModulesSize / analysis.totalSize) * 100).toFixed(2)}%)</p>
    <p><strong>React Native:</strong> ${formatBytes(analysis.reactNativeSize)} (${((analysis.reactNativeSize / analysis.totalSize) * 100).toFixed(2)}%)</p>
  </div>

  <h2>Top Dependencies</h2>
  <table>
    <thead>
      <tr>
        <th>Package</th>
        <th>Size</th>
        <th>% of Bundle</th>
        <th>Modules</th>
      </tr>
    </thead>
    <tbody>
      ${analysis.packages
        .slice(0, 20)
        .map(
          (pkg) => `
        <tr>
          <td>${pkg.name}${pkg.version ? ` (${pkg.version})` : ''}</td>
          <td>${formatBytes(pkg.size)}</td>
          <td>${pkg.percentage.toFixed(2)}%</td>
          <td>${pkg.modules.length}</td>
        </tr>
      `
        )
        .join('')}
    </tbody>
  </table>

  ${
    analysis.optimizations.length > 0
      ? `
  <h2>🎯 Optimization Suggestions</h2>
  ${analysis.optimizations
    .map(
      (opt) => `
    <div class="optimization ${opt.severity}">
      <h3>${opt.suggestion}</h3>
      <p><strong>Package:</strong> ${opt.package}</p>
      <p><strong>Current Size:</strong> ${formatBytes(opt.currentSize)}</p>
      <p><strong>Potential Savings:</strong> ${formatBytes(opt.potentialSavings)}</p>
      ${opt.alternative ? `<p><strong>Alternative:</strong> ${opt.alternative}</p>` : ''}
    </div>
  `
    )
    .join('')}
  `
      : ''
  }

  ${
    analysis.duplicates.length > 0
      ? `
  <h2>⚠️ Duplicate Packages</h2>
  <table>
    <thead>
      <tr>
        <th>Package</th>
        <th>Versions</th>
        <th>Wasted Size</th>
      </tr>
    </thead>
    <tbody>
      ${analysis.duplicates
        .map(
          (dup) => `
        <tr>
          <td>${dup.name}</td>
          <td>${dup.versions.length}</td>
          <td>${formatBytes(dup.totalWaste)}</td>
        </tr>
      `
        )
        .join('')}
    </tbody>
  </table>
  `
      : ''
  }

  <p style="text-align: center; color: #666; margin-top: 40px;">
    Generated by React Native Bundle Analyzer
  </p>
</body>
</html>
    `;

    fs.writeFileSync(outputPath, html, 'utf-8');
  }

  /**
   * Generate a markdown report
   */
  static generateMarkdownReport(analysis: BundleAnalysis, outputPath: string): void {
    const md = `# React Native Bundle Analysis Report

## Summary

- **Total Bundle Size:** ${formatBytes(analysis.totalSize)}
- **Your Code:** ${formatBytes(analysis.yourCodeSize)} (${((analysis.yourCodeSize / analysis.totalSize) * 100).toFixed(2)}%)
- **node_modules:** ${formatBytes(analysis.nodeModulesSize)} (${((analysis.nodeModulesSize / analysis.totalSize) * 100).toFixed(2)}%)
- **React Native:** ${formatBytes(analysis.reactNativeSize)} (${((analysis.reactNativeSize / analysis.totalSize) * 100).toFixed(2)}%)

## Top Dependencies

| Package | Size | % of Bundle | Modules |
|---------|------|-------------|---------|
${analysis.packages
  .slice(0, 20)
  .map(
    (pkg) =>
      `| ${pkg.name}${pkg.version ? ` (${pkg.version})` : ''} | ${formatBytes(pkg.size)} | ${pkg.percentage.toFixed(2)}% | ${pkg.modules.length} |`
  )
  .join('\n')}

${
  analysis.optimizations.length > 0
    ? `
## Optimization Suggestions

${analysis.optimizations
  .map(
    (opt, i) => `
### ${i + 1}. ${opt.suggestion}

- **Package:** ${opt.package}
- **Current Size:** ${formatBytes(opt.currentSize)}
- **Potential Savings:** ${formatBytes(opt.potentialSavings)}
${opt.alternative ? `- **Alternative:** ${opt.alternative}` : ''}
`
  )
  .join('\n')}
`
    : ''
}

${
  analysis.duplicates.length > 0
    ? `
## Duplicate Packages

| Package | Versions | Wasted Size |
|---------|----------|-------------|
${analysis.duplicates.map((dup) => `| ${dup.name} | ${dup.versions.length} | ${formatBytes(dup.totalWaste)} |`).join('\n')}
`
    : ''
}

---
*Generated by React Native Bundle Analyzer*
    `;

    fs.writeFileSync(outputPath, md, 'utf-8');
  }

  /**
   * Generate a CSV report of packages
   */
  static generateCsvReport(analysis: BundleAnalysis, outputPath: string): void {
    const csv = [
      'Package,Version,Size (bytes),Percentage,Modules',
      ...analysis.packages.map(
        (pkg) => `"${pkg.name}","${pkg.version || ''}",${pkg.size},${pkg.percentage.toFixed(4)},${pkg.modules.length}`
      ),
    ].join('\n');

    fs.writeFileSync(outputPath, csv, 'utf-8');
  }
}
